apiVersion: v1
kind: Service
metadata:
  name: ml-inference-svc
  namespace: ml-inference
spec:
  type: ClusterIP
  selector:
    app: ml-inference
  ports:
    - name: http
      port: 80
      targetPort: 8000
